package analysis;

/**
 * Created by Nik on 04-11-2015
 */
public enum Metric {
	CLASS_LOC,
	CLASS_SUPERCLASSES,
	CLASS_METHODS,
	CLASS_ACCESSORS,
	CLASS_LCOM,
	CLASS_METHODS_NO_PARAMS,
	CLASS_PUBLIC_FIELDS,
	SUBROUTINE_LOC,
	SUBROUTINE_PARAMS,
	SUBROUTINE_AID,
}
